# Config for preference_engine_XGBoost

import os
from pathlib import Path

_ENGINE_DIR = Path(__file__).resolve().parent.parent
_DEFAULT = _ENGINE_DIR / "artifacts" / "model.joblib"
# Modal sets PREFERENCE_ENGINE_XGBOOST_MODEL_PATH so the container finds the model
DEFAULT_MODEL_PATH = Path(os.environ.get("PREFERENCE_ENGINE_XGBOOST_MODEL_PATH", str(_DEFAULT)))
DEFAULT_TRAIN_SAMPLES = 100_000
DEFAULT_RANDOM_STATE = 42
DEFAULT_CLASSIFIER = "xgboost"
LOGISTIC_C = 1.0
TREE_MAX_DEPTH = 5
TREE_MIN_SAMPLES_LEAF = 20
XGBOOST_N_ESTIMATORS = 200
XGBOOST_MAX_DEPTH = 6
XGBOOST_LEARNING_RATE = 0.05
XGBOOST_SUBSAMPLE = 0.8
XGBOOST_COLSAMPLE_BYTREE = 0.8
XGBOOST_REG_ALPHA = 0.1
XGBOOST_REG_LAMBDA = 1.0
